### ISSUE TITLE
Enhancing the Service Section

### ISSUE THREAD

**Issue by thenormalcoder** [divyanshudhruv/Minifolio#101]
I want to make Services section look better looking through Tailwind CSS and React....
![Screenshot 2024-10-07 192124](https://github.com/user-attachments/assets/317cdaa5-e624-421e-bb44-ae4e052376c
After Some needed changes it will definitely look impressive and more presentable..
So assign this issue to me so that I can make my first contribution in Hacktober fest 2024..

**Comment by divyanshudhruv** [comment]
@thenormalcoder sure i'll assign it to you, but if you have any screenshot or and temporary design, you can share it. Good luck
