### ISSUE TITLE
Adding a blog section in portfolio template maker

### ISSUE THREAD

**Issue by Aakansha-Chavan** [divyanshudhruv/Minifolio#104]
Hello! I would like to add a blog section in your project, Can you please assign this issue to me?

**Comment by divyanshudhruv** [comment]
@Aakansha-Chavan assignee to you. Good luck, but make sure that you follow the website's theme and font styles.

**Comment by jenyyy4** [comment]
@divyanshudhruv i would like to work on this issue, please assign it to me.

We need to add a "Blog" section to the portfolio template to allow users to showcase their articles, tutorials, or personal updates. This feature will enhance the portfolio’s content and SEO value by sharing valuable insights, experiences, and knowledge.

**Comment by divyanshudhruv** [comment]
@Aakansha-Chavan and update ? Can you share the screenshot if the UI is completed ? Thankyou

**Comment by Aakansha-Chavan** [comment]
Yes, actually in sometime I am actually going to open a pull request.

**Comment by Aakansha-Chavan** [comment]
Hello @divyanshudhruv I have opened a pull request.
