### ISSUE TITLE
Adding a navbar

### ISSUE THREAD

**Issue by jenyyy4** [divyanshudhruv/Minifolio#105]
### Issue: Add a Navigation Bar (Navbar)

**Description:**
We need to add a basic navigation bar (navbar) to improve site navigation and user experience. This will help users move between different sections of the website easily.

**Acceptance Criteria:**
- The links should have a hover effect that changes the background color.
- The brand/logo should be aligned on the left, and the links should be aligned on the right.

**Task List:**
1. Create a `navbar` container in the HTML file.
2. Add CSS styles to design the navbar with appropriate padding, colors, and fonts.
3. Add hover effects for the navbar links.

**Example of expected structure:**

```html
<nav class="navbar">
  <div class="navbar-logo">Brand</div>
  <div class="navbar-right">
    <a href="#home">Home</a>
    <a href="#about">About</a>
    <a href="#services">Services</a>
    <a href="#contact">Contact</a>
  </div>
</nav>

**Comment by jenyyy4** [comment]
@divyanshudhruv i would like to work on this issue, please assign it to me.

**Comment by divyanshudhruv** [comment]
@jenyyy4 I think the landing page of the portfolio should be clean and minimal without the navbar at the top. But if we need a navbar we can add it as a hover button which expands on clicking to its left or right on either left top or right top side of the portfolio. I hope you understand.

 I'm assigning it to you, and make sure you follow the website's theme and don't styles. You can share a screen shot or a short video  after completing the navbar and before opening the pull request. Good luck

**Comment by jenyyy4** [comment]
I've streamlined the navigation experience with a sleek, modern design with the theme of the website intact.
Please let me know if you need any modifications.
Happy to help!
Uploading Navbar Screen Rec.mov…

**Comment by jenyyy4** [comment]
I've streamlined the navigation experience with a sleek, modern design with the theme of the website intact.
Please let me know if you need any modifications.
Happy to help!

<img width="1440" alt="Screenshot 2024-10-08 at 12 40 02 AM" src="https://github.com/user-attachments/assets/f821db03-a6fc-402b-87c9-26d666978ff7">
<img width="1440" alt="Screenshot 2024-10-08 at 12 39 56 AM" src="https://github.com/user-attachments/assets/468fb9a3-44b4-4590-b897-848bf390b723">

**Comment by jenyyy4** [comment]
@divyanshudhruv should i open a pull request?

**Comment by divyanshudhruv** [comment]
#111 added the hacktoberfest-accepted label. 😃
