### ISSUE TITLE
Create a Custom Logo for the Website

### ISSUE THREAD

**Issue by jenyyy4** [divyanshudhruv/Minifolio#106]
### Issue: Create a Custom Logo for the Website

**Description:**
We need a custom logo to establish a recognizable brand identity for the website. The logo should be simple, modern, and scalable for different uses (web, social media, favicon, etc.).

**Acceptance Criteria:**
- The logo should reflect the brand’s values and identity.
- It should be delivered in multiple formats: **SVG** (for scalability), **PNG** (for web), and **ICO** (for favicon).

**Task List:**
Create a simple and modern logo design.

**Comment by jenyyy4** [comment]
@divyanshudhruv i would like to work on this, please assign it to me.

**Comment by divyanshudhruv** [comment]
@jenyyy4 sure. Assigned to you! Good luck :)

**Comment by jenyyy4** [comment]
![minifolio](https://github.com/user-attachments/assets/77fee5e0-4cf1-4434-8bc0-65045b0af3ad)

Here's the logo for your portfolio website i think it aligns well with the theme of your website.
Please let me know if you need any changes.
Thanks!

**Comment by jenyyy4** [comment]
@divyanshudhruv should i open a pull request?

**Comment by divyanshudhruv** [comment]
@jenyyy4 sure

**Comment by divyanshudhruv** [comment]
@jenyyy4 please resolve any conflict present in the file and then create a new directory named "logo" and then put the image of the logo in that directory with multiple formats (png,ico,svg). Good luck

**Comment by jenyyy4** [comment]
@divyanshudhruv i've opened a pull request, could you please check?
