### ISSUE TITLE
Adding a Contact me section

### ISSUE THREAD

**Issue by kumartushar0605** [divyanshudhruv/Minifolio#107]

**Comment by kumartushar0605** [comment]
@divyanshudhruv brother please assign me

**Comment by Abhishek86798** [comment]
@divyanshudhruv I would like to work on this, please assign it to me.

**Comment by Divii2205** [comment]
Heyy @divyanshudhruv!
I am looking forward on working on this issue as I am personally interested in frontend development!
Could you please assign me the issue so that I can start working on it right away!
Thank you!

**Comment by divyanshudhruv** [comment]
@kumartushar0605 any update ?

**Comment by kumartushar0605** [comment]
@divyanshudhruv brother i have added contact section now please merge it brother

**Comment by divyanshudhruv** [comment]
@kumartushar0605 ok thnx, I'll merge it

**Comment by kumartushar0605** [comment]
@divyanshudhruv bro please merge it

**Comment by divyanshudhruv** [comment]
@kumartushar0605  merged.
