### ISSUE TITLE
Add a Separate project section to showcase skills and project 

### ISSUE THREAD

**Issue by VesperAkshay** [divyanshudhruv/Minifolio#110]
### Description
We would like to enhance our project by adding a dedicated section for showcasing individual skills and projects. This will provide better visibility for contributors and allow users to highlight their expertise and work effectively.

### Requirements
- Create a new section titled "Projects" in the main layout.
- Each project should include:
  - Project title
  - Brief description
  - Technologies used
  - Link to the project (if applicable)
  - Option to include images or screenshots
- Ensure the section is responsive and visually appealing.
- Update the navigation menu to include a link to the new Projects section.

### Acceptance Criteria
- The Projects section is clearly visible on the main page.
- Each project is displayed with all required information.
- Navigation to the Projects section is seamless.
- The design is consistent with the existing layout.

### Additional Notes
- Consider using cards or grid layout for project display.
- Please ensure to follow the existing coding standards and guidelines.

### Labels
- enhancement
- hacktoberfest
- hacktoberfest-accepted

**Comment by AfubeAngel** [comment]
Hello. I would love to work on this. What is a portfolio without evidence of work done displayed in the projects section? @VesperAkshay

**Comment by divyanshudhruv** [comment]
@AfubeAngel @VesperAkshay this issue is already being worked on. Please see it here-
#96 #103 . But you can modify the existing code present there and make it better. Good luck

**Comment by AfubeAngel** [comment]
![Screenshot (3)](https://github.com/user-attachments/assets/d3bff02d-b457-4945-b53b-de64f7116696)
@divyanshudhruv I had this in mind for the project display under the service section

PLease advice on how I should proceed, or should I abandon this totally?

**Comment by divyanshudhruv** [comment]
@AfubeAngel this looks pretty cool. You can work on it 😄. Good luck. You can open the PR asap

**Comment by AfubeAngel** [comment]
Oh thank you, I'll proceed accordingly

**Comment by AfubeAngel** [comment]
Raised a pull request last night. Please review PR #126
