### ISSUE TITLE
Simplify Component Usage with Tailwind/Bootstrap Integration

### ISSUE THREAD

**Issue by Riddhi050803** [divyanshudhruv/Minifolio#114]
Description: To speed up development and ensure consistent styling, we can integrate Tailwind CSS or Bootstrap. This will allow the use of pre-built, responsive components and utility classes, reducing the need for manual CSS.

Benefits:

Faster development with pre-built components.
Consistent design across the project.
Easy customization with utility classes.

**Comment by Riddhi050803** [comment]
Assign it to me, I will change the manual CSS to tailwind CSS @divyanshudhruv

**Comment by divyanshudhruv** [comment]
@Riddhi050803 we will change it later. Currently we are focusing on the basic UI or the portfolio. But thank you for the idea :)
