### ISSUE TITLE
Add Social Sections 

### ISSUE THREAD

**Issue by Mukesh-ghildiyal** [divyanshudhruv/Minifolio#116]
i just want to create the all the social-media section

**Comment by Aryan-AAP** [comment]
ok am talking this so you want links to x github and other right 
![Screenshot 2024-10-08 212135](https://github.com/user-attachments/assets/557b290b-1a27-4cdf-80ce-d580f751b748)

the one in image will work right

**Comment by divyanshudhruv** [comment]
that seems cool, you can work on it

**Comment by hemangtk** [comment]
Heyy @divyanshudhruv 
is this issue already assigned or can i also work on it further?

**Comment by divyanshudhruv** [comment]
@Aryan-AAP any updates ?
