### ISSUE TITLE
✨Add a person image at the start of landing page

### ISSUE THREAD

**Issue by meet244** [divyanshudhruv/Minifolio#118]
Enhance the landing page by adding a friendly, engaging image of a person to create a welcoming atmosphere.

**Comment by divyanshudhruv** [comment]
@meet244 can you share a temporary screen shot so that we can know how to proceed further?

**Comment by meet244** [comment]
![image](https://github.com/user-attachments/assets/58d94b03-1b9e-4f52-a059-0fde8cbbbbcd)

Something like this...

**Comment by meet244** [comment]
I am working on it.
