### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by Dhavisco** [divyanshudhruv/Minifolio#12]
The button 'click me' on the mobile view is not well structured. 
You cam reduce the padding. The button is not consistent also. It should fit with the 'know me' button style.
Most of the sections have too many paddings and they are not centered properly like the "about" <h> tag especially on the mobile view.

**Comment by Dhavisco** [comment]
I would like to assign it to myself.

**Comment by divyanshudhruv** [comment]
Ok

**Comment by Dhavisco** [comment]
Yes

**Comment by Dhavisco** [comment]
I will push the update at the start of the hacktoberfest

**Comment by divyanshudhruv** [comment]
Ok.

**Comment by divyanshudhruv** [comment]
Hello, please visit [here](https://github.com/divyanshudhruv/Minifolio/issues/1#issuecomment-1739523243)

**Comment by Dhavisco** [comment]
Thank you. Kindly add the label hacktoberfest

**Comment by Ayaz-Mohammed-Khan** [comment]
Hello there as I can see this issue is assigned already but is not resolved yet so I would like to work on it assign it to me

**Comment by karankoder** [comment]
Please assign me some issue. @divyanshudhruv
