### ISSUE TITLE
Adding a background color to the nav bar

### ISSUE THREAD

**Issue by Divii2205** [divyanshudhruv/Minifolio#121]
**🔥 Enhancement**

**🫤 Description**

Adding a background color to the nav bar

**📍 Use Case**

A background color helps the nav bar stand out from the rest of the content on the page. This makes it easier for users to locate navigation elements quickly. It enhances readability. 

**🤔 To-Do**

Adding a background color matching the theme of the website.

🌱 Contribute

I want to contribute to this issue @divyanshudhruv

**Comment by NechamaSopher** [comment]
@Divii2205 Hi, I will love to do this, Can you please assign it to me?

**Comment by divyanshudhruv** [comment]
@Divii2205 you can open pull request in development branch after forking the main repo :)

**Comment by NechamaSopher** [comment]
Sorry @Divii2205 I didn't realize you wanted to do it.
I was thinking of doing something like this (it is ready for pr if you want..):  
![image](https://github.com/user-attachments/assets/a732c13f-c73c-46e8-b11a-833b343bbf8c)

**Comment by divyanshudhruv** [comment]
> Sorry @Divii2205 I didn't realize you wanted to do it. I was thinking of doing something like this (it is ready for pr if you want..): ![image](https://private-user-images.githubusercontent.com/39656037/374911320-a732c13f-c73c-46e8-b11a-833b343bbf8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NjkyODQsIm5iZiI6MTcyODQ2ODk4NCwicGF0aCI6Ii8zOTY1NjAzNy8zNzQ5MTEzMjAtYTczMmMxM2YtYzczYy00NmU4LWIxMWEtODMzYjM0M2JiZjhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDEwMTYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkOTc2OGQ3OTI0ZTI3YzAxZDNjNGM5MTBiY2E2M2NlMGE4MThiZTRlZTQwNzZkZGJmYjk4NWQwNGUwYWJkOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KzFAarnFEm11JFrpTc3b0q6g0CJAO7ksc64nHW2zOew)

@NechamaSopher you can open PR into development branch

**Comment by Divii2205** [comment]
> @Divii2205 you can open pull request in development branch after forking the main repo :)

I have opened a pull request. Please review it. Thank you @divyanshudhruv
