### ISSUE TITLE
Hamburger Menu on Mobile Devices

### ISSUE THREAD

**Issue by tanish0912** [divyanshudhruv/Minifolio#124]
<img width="330" alt="Screenshot 2024-10-09 at 12 12 43 AM" src="https://github.com/user-attachments/assets/ea8d30f1-f8ab-4ba1-92cc-06ff1de2868e">
he Portfolio lacks a clean look on mobile.
I am planning to add hamburger menu on mobile devices which will website clean and professional look on mobile.

**Comment by tanish0912** [comment]
Please assign me this issue.

**Comment by divyanshudhruv** [comment]
hi, @tanish0912 actually this issue is being worked on by someone else... Sorry... Buy you can work on other customizations

**Comment by divyanshudhruv** [comment]
@tanish0912
