### ISSUE TITLE
Add new Animation and effect with GSAP  for more interactive ui experience 

### ISSUE THREAD

**Issue by MOHIT-IITP** [divyanshudhruv/Minifolio#129]
Work to do:
I intend to use GSAP's ScrollTrigger to create an interactive effect where elements change their position dynamically as the user scrolls, achieving a smooth parallax effect for a more immersive experience.

Please assign me and mark it as Hacktoberfest

**Comment by divyanshudhruv** [comment]
@MOHIT-IITP sure
