### ISSUE TITLE
Multiple css file

### ISSUE THREAD

**Issue by Dhavisco** [divyanshudhruv/Minifolio#13]
We have the button.css and style.css in both the cas folder amd the primary folder.
Delete the outer css files so as to follow the tree diagram specified in the project.

**Comment by divyanshudhruv** [comment]
Ok

**Comment by Thanush19** [comment]
can i fix this  @Dhavisco

**Comment by Dhavisco** [comment]
> can i fix this @Dhavisco

You can ask @divyanshudhruv

**Comment by divyanshudhruv** [comment]
I think let @Dhavisco fix this, as he opened the issue.. @Thanush19 you can try to fix other bug if present

**Comment by Dhavisco** [comment]
Noted. I will work on it too

**Comment by divyanshudhruv** [comment]
Good luck

**Comment by divyanshudhruv** [comment]
Hello, please visit [here](https://github.com/divyanshudhruv/Minifolio/issues/1#issuecomment-1739523243)

**Comment by divyanshudhruv** [comment]
When will you open the pr ? @Dhavisco

**Comment by Dhavisco** [comment]
Yes. Happy Hacktoberfest

**Comment by Dhavisco** [comment]
Pls add the hacktoberfest logo

**Comment by divyanshudhruv** [comment]
Ok
