### ISSUE TITLE
Navbar Content Overlapping

### ISSUE THREAD

**Issue by Deekshashakyawal** [divyanshudhruv/Minifolio#138]
The navbar content and page content gets overlapped when scrolling. 
Please assign me this issue under Hacktoberfest. 

![Screenshot 2024-10-09 170248](https://github.com/user-attachments/assets/8f134ef8-e4f9-4a98-81e5-151f50a6fdc5)

**Comment by marsianjohncarter** [comment]
@Deekshashakyawal I am pretty sure that is was meant to be that way. The navbar is made to be transparent purposefully.

**Comment by divyanshudhruv** [comment]
yep,
