### ISSUE TITLE
✨ Add skills section

### ISSUE THREAD

**Issue by divyanshudhruv** [divyanshudhruv/Minifolio#14]
## 🫤 Description

<br>

> Adding skills section to the portfolio

<br>

## 📍 Use Case

<br>

> It will make portfolio look more attractive

> It will show our skills in different languages

<br>

## 📦 Additional Information

<br>

> **`Icons:`** Ionicons and Remixicon

<br>

## ✋🏻 Upvotes

<br>

> If you support this feature request, add a 👍🏻.

<br>

## 🤔 To-Do

<br>

> If you have specific tasks or action items related to this feature request, list them here.

<br>

## 🌱 Contribute

<br>

> - [x] I want to contribute 

  <br>
  
## 📌 Related Issue

<br>

> Link to other issues related to this problem

**Comment by newtoallofthis123** [comment]
Hey! Can I be assigned this? I would add a beautifully designed skills section!

**Comment by divyanshudhruv** [comment]
Hello @newtoallofthis123, actually I am doing this feature. So, unfortunately I cannot assign this to you. But you may search the issues and try to work on different features. Good luck...

**Comment by newtoallofthis123** [comment]
Sure! Actually, I noticed that there is no projects section or a social section. Want me to add anyone of those?

**Comment by divyanshudhruv** [comment]
newtoallofthis123, there is some confusion as one developer had already assigned the task to himself .See #5 . So let me create different issue for different sections then I can assign you both, which you both want.

**Comment by AMANMUHAL** [comment]
No problem ,, can i make issue of My projects/ Contact Me

**Comment by Satyam1616** [comment]
Hey can you assign me this task I want to contribute
