### ISSUE TITLE
Differentiating different sections of the page

### ISSUE THREAD

**Issue by Divii2205** [divyanshudhruv/Minifolio#140]
🔥 **Enhancement**

🫤 **Description**

Adding alternate background colors for the various sections

📍 **Use Case**

Different background colors for different sections help:
1. separate content
2. enhance readability
3. increase user engagement by breaking monotony
4. distinguish different sections

🤔 **To-Do**

Adding a background color for the **about** section

🌱 **Contribute**

I want to contribute to this issue @divyanshudhruv 

![SectionDifferentiator](https://github.com/user-attachments/assets/6ea9544d-45c7-4f75-af11-9facb8ee700a)

**Comment by divyanshudhruv** [comment]
@Divii2205 I think the background should remain white(darkmode also) for the time because new PRs are appearing and we need major update to the portfolio. So after all the sections are created, we can work on this issue. Thankyou
