### ISSUE TITLE
Add light and dark theme

### ISSUE THREAD

**Issue by pranavsuriya-sr** [divyanshudhruv/Minifolio#141]
Add light and dark theme button in the navbar, and provide the functionality.

**Comment by pranavsuriya-sr** [comment]
Please assign this issue to me.

**Comment by Abhinab04** [comment]
@divyanshudhruv i opened the pr ,for dark theme ,kindly review it,
thankyou in advance

**Comment by divyanshudhruv** [comment]
#152
