### ISSUE TITLE
Add "Education" to the nav bar

### ISSUE THREAD

**Issue by Divii2205** [divyanshudhruv/Minifolio#143]
### Issue: Add "Education" label to the nav bar

**Description:** 

Due to the addition of a new section "Education". It must be mentioned in the nav bar and linked to its respective section. 

**Task list:**
1. Create a label `Education` in the navbar 
2. Link it to the resepective "Education" section

**Comment by Divii2205** [comment]
@divyanshudhruv I wish to append this change in the nav bar. Kindly let me know if I can take up this task. Thank you!

**Comment by divyanshudhruv** [comment]
Yea sure, I'll merge this PR first...

**Comment by Divii2205** [comment]
@divyanshudhruv I have opened a pull request for the same. Kindly check and let me know if anything needs to be changed. Thank you!
