### ISSUE TITLE
adding images

### ISSUE THREAD

**Issue by ParvamShah1** [divyanshudhruv/Minifolio#149]
there no space to add images in the entire portfolio
adding an image on the home page would make it more presentable for the user.
also adding few more images in the sections below.
These changes would make the template more user friendly and ideal portfolio for a user.
please assign me this issue,i would like to work on it.

**Comment by marsianjohncarter** [comment]
Related: #118

**Comment by divyanshudhruv** [comment]
This is already in progress.
