### ISSUE TITLE
✨ Add project section

### ISSUE THREAD

**Issue by divyanshudhruv** [divyanshudhruv/Minifolio#15]
## 🫤 Description

<br>

> Adding project section in the portfolio

<br>

## 📍 Use Case

<br>

> It will make portfolio look more attractive

> It will showcase our completed projects and accomplishments.

<br>

## 📦 Additional Information

<br>

> **`Images:`** Should be of same size as suggested to prevent the chance of overflow

<br>

## ✋🏻 Upvotes

<br>

> If you support this feature request, add a 👍🏻.

<br>

## 🤔 To-Do

<br>

> If you have specific tasks or action items related to this feature request, list them here.

<br>

## 🌱 Contribute

<br>

> - [] I want to contribute 

  <br>
  
## 📌 Related Issue

<br>

> #6

**Comment by hp1004** [comment]
hey @divyanshudhruv , I want to contribute

**Comment by divyanshudhruv** [comment]
@hp1004 Ok As many requests are coming for addition of sections, We are currently dividing the work between the contributors. Wait for some time until all contributors agree

**Comment by Kapileswar-Moharana** [comment]
Assign me this issue under Hcktoberfest'23 @divyanshudhruv

**Comment by divyanshudhruv** [comment]
> Assign me this issue under Hcktoberfest'23 @divyanshudhruv

I am assigning it to myself and you

**Comment by shreyashnalawade1** [comment]
Hey, I have a suggestion and would Like to implement it If you agree my idea is to take users' pined repos or recently updated repos from their github profile and display them in the project section not sure how you guys are going to implement it right now ? let me know if I can work on it

**Comment by shreyashnalawade1** [comment]
Can check out this issue on a similar repo 
[here](https://github.com/arifszn/gitprofile/issues/432)

**Comment by Kapileswar-Moharana** [comment]
@divyanshudhruv hey check the look will it be good , if then it's done sir... 

![Screenshot 2023-10-16 023303](https://github.com/divyanshudhruv/Minifolio/assets/129049677/664c5fdf-4fd4-473d-9800-4111206c250a)

**Comment by Kapileswar-Moharana** [comment]
@divyanshudhruv  Check it sir is this type of look will be good for you or not?

**Comment by Kapileswar-Moharana** [comment]
> It's ok but wait for some more days for confirmation

Okay But only 14 Days are left to end the Hacktoberfest.

Okay take your time but how many days ? @divyanshudhruv

**Comment by divyanshudhruv** [comment]
3-4 days only. Actually I am a bit busy in studies so I can't see the issues and the message.

**Comment by divyanshudhruv** [comment]
Added the hacktoberfest-accepted label, will merge soon

**Comment by Kapileswar-Moharana** [comment]
???? @divyanshudhruv

**Comment by Kapileswar-Moharana** [comment]
@divyanshudhruv  project section krogee sirr yaa main Karu ? Kuch bologe..?

**Comment by Kapileswar-Moharana** [comment]
@divyanshudhruv ? What about Project Section

**Comment by divyanshudhruv** [comment]
@Kapileswar-Moharana actually I am not online for much time due to upcoming exams. Btw you can open pr

**Comment by Kapileswar-Moharana** [comment]
> @Kapileswar-Moharana actually I am not online for much time due to upcoming exams. Btw you can open pr

Fine Sir

**Comment by Kapileswar-Moharana** [comment]
> @Kapileswar-Moharana actually I am not online for much time due to upcoming exams. Btw you can open pr

@divyanshudhruv ok check that contact section as I make the changes on main branch that's why it's displaying error while working another issue...so..check contact section pr , project section code already ready...just after I am gonna raise the issue..sir

**Comment by Kapileswar-Moharana** [comment]
@divyanshudhruv Sir kal 12 pm kabkaa chhhalaa gaya... ajj 30th haii Thhodaa Check krengee....Sir...Codes...

**Comment by Kapileswar-Moharana** [comment]
> @divyanshudhruv Sir kal 12 pm kabkaa chhhalaa gaya... ajj 30th haii Thhodaa Check krengee....Sir...Codes...
...
