### ISSUE TITLE
Hide the navbar when user scrolls down.

### ISSUE THREAD

**Issue by marsianjohncarter** [divyanshudhruv/Minifolio#156]
I want to add some css styling to make the navbar dissapear when the user scrolls down and appear when the user scrolls up.

**Comment by divyanshudhruv** [comment]
@marsianjohncarter sure. You can share a small video related to it before creating pull request. Good luck

**Comment by marsianjohncarter** [comment]
@divyanshudhruv here is how it turned out:


https://github.com/user-attachments/assets/0e806299-0ca8-4d9b-9136-f1ec5a64ed4a

**Comment by marsianjohncarter** [comment]
@divyanshudhruv Should I open PR or what until 16/10?

**Comment by divyanshudhruv** [comment]
You can wait till 16/10 because there are a lot of code that needs to be fixed.Thank you and good luck

**Comment by marsianjohncarter** [comment]
> You can wait till 16/10 because there are a lot of code that needs to be fixed.Thank you and good luck

For sure. I checked how the project look with all of the additions, and found that it has turned a bit "Bigafolio". 

Thank you for your commitment!
