### ISSUE TITLE
The services cards in the services section don't have their text aligned.

### ISSUE THREAD

**Issue by Pujan-khunt** [divyanshudhruv/Minifolio#158]
As it can be clearly observed that the text is the cards are not aligned.

![image](https://github.com/user-attachments/assets/b45a6d73-ac23-4641-8011-24e03e729df4)

Please assign this issue to me under the Hacktoberfest Label @divyanshudhruv . Thank You.

**Comment by divyanshudhruv** [comment]
@Pujan-khunt sure
