### ISSUE TITLE
✨ Add contact section

### ISSUE THREAD

**Issue by divyanshudhruv** [divyanshudhruv/Minifolio#16]
## 🫤 Description

<br>

> Adding contact section to the portfolio

<br>

## 📍 Use Case

<br>

> Visitors will have multiple ways to get in touch with us.

<br>

## 📦 Additional Information

<br>

> **`Backend:`** Backend for getting the contact inputs and outputs.

<br>

## ✋🏻 Upvotes

<br>

> If you support this feature request, add a 👍🏻.

<br>

## 🤔 To-Do

<br>

> If you have specific tasks or action items related to this feature request, list them here.

<br>

## 🌱 Contribute

<br>

> - [x] I want to contribute 

  <br>
  
## 📌 Related Issue

<br>

> #6

**Comment by divyanshudhruv** [comment]
Ok, good luck

**Comment by divyanshudhruv** [comment]
Hello, please visit [here](https://github.com/divyanshudhruv/Minifolio/issues/1#issuecomment-1739523243)

**Comment by divyanshudhruv** [comment]
Any updates @Kapileswar-Moharana

**Comment by Kapileswar-Moharana** [comment]
> Any updates @Kapileswar-Moharana 

Back to top buttom is done actually I think if I add progress to that back top top button then how it will perform just working on that... if it's not perform well then will update you first if some more changes you want then will do it , otherwise raise pr by tonight

**Comment by Kapileswar-Moharana** [comment]
@divyanshudhruv Also I think I should have created an issue regarding the Nav bar (because dono ak hi batt haii navv barr krkee section pura karoo yaa fir section krkee nav bar) then I will add a nav bar top right of portfolio n clicking on sections it will take u it's respective sections should I raise the issue?

**Comment by divyanshudhruv** [comment]
@Kapileswar-Moharana actually I am creating th3 navbar, I thought I should create the navbar as everyone is confused that who will create. So, I can't assign the issue. Btw good luck,you can work on different issue

**Comment by Kapileswar-Moharana** [comment]
> @Kapileswar-Moharana actually I am creating th3 navbar, I thought I should create the navbar as everyone is confused that who will create. So, I can't assign the issue. Btw good luck,you can work on different issue

Okk

**Comment by Kapileswar-Moharana** [comment]
@divyanshudhruv Check  it , n say what extra changes n all that you want, after completing this one i will open pr by tonight

![Screenshot 2023-10-11 004211](https://github.com/divyanshudhruv/Minifolio/assets/129049677/835adc0b-0e5c-4f4f-9f5d-9755835d9ff4)

**Comment by Kapileswar-Moharana** [comment]
@divyanshudhruv  ?

**Comment by divyanshudhruv** [comment]
Ok, you can make new page.

**Comment by Kapileswar-Moharana** [comment]
@divyanshudhruv Hey check it actually doesn't suit it to open a new page for it I think a page portfolio should be good here is the Contact Us section screenshot tell me any extra changes you want, Kindly tell me all the changes you wanted at once OK, Form should i add, Actually i asked one my teacher he said Contact Form only be added in organisational website, Providing E mail is enough, what is your Concent?


![Screenshot 2023-10-16 021437](https://github.com/divyanshudhruv/Minifolio/assets/129049677/f1b59c16-9ac1-4b1e-b8c3-fe9a9a0ace87)

**Comment by Kapileswar-Moharana** [comment]
@divyanshudhruv  Is it okay then PR Raise kardoo  ? Ya Aur kuch changes baki hai ?

**Comment by Kapileswar-Moharana** [comment]
@divyanshudhruv ?

**Comment by Kapileswar-Moharana** [comment]
@divyanshudhruv ?

**Comment by Kapileswar-Moharana** [comment]
@divyanshudhruv Aree Sir Aur kuch changes chahiyee yaa Pr Raise karuu 8 din bachhe haii ?

**Comment by divyanshudhruv** [comment]
@Kapileswar-Moharana I think, its ok, No need for any changes . Will collaborate afterwards

**Comment by Kapileswar-Moharana** [comment]
@divyanshudhruv so  now I am opening the pr

**Comment by Kapileswar-Moharana** [comment]
@divyanshudhruv hey main abhi fork ko update kiyaa  to aisee diikhaa rahaa appne check kiyaa thha ?


![Screenshot 2023-10-22 202916](https://github.com/divyanshudhruv/Minifolio/assets/129049677/48c84505-e104-4fd8-8d7b-c4b8fd6b9cc7)

**Comment by Kapileswar-Moharana** [comment]
@divyanshudhruv hey can you check the pr #79 and merge it.If any changes you want then say.

**Comment by Kapileswar-Moharana** [comment]
@divyanshudhruv ?

**Comment by Kapileswar-Moharana** [comment]
@divyanshudhruv  Sir when will it get merged? How Much Later?

**Comment by Kapileswar-Moharana** [comment]
@divyanshudhruv I have Completed the work on the Project Section, As I Opened PR By working on the Main Branch Show it showed some issues While Opening PR for the Project Section, You Merge If there is not an error after Only I can Open PR For Project Section.

**Comment by Kapileswar-Moharana** [comment]
@divyanshudhruv Aree Sirr Chall Kyaa rahaa haio... meree code mainn koii bugs  hai too bolona... ajj krunhga kall paakkaa karadungaa.. mainn kyaa aiaae har din karta rahu....Ajj 30th Oct haii.. kall last jo bhhii bugss haii woo bbadd main bhhii fixx lkiyaa jaa saktaa haii na ...Kyaa Sir harr din msg karuu ki surr check kkrooo... ? @divyanshudhruv Can You please Check it sir... its 30 th oct today.., If there is bugg in your code then i will fix it... You just check my codes... if there is any error then say me .. i wwill fix it .. otherwise please merge soon...

**Comment by Kapileswar-Moharana** [comment]
@divyanshudhruv Ok then Close these Related Issues...
