### ISSUE TITLE
Fix the navigation bar for mobile devices.

### ISSUE THREAD

**Issue by TheSoumenMondal** [divyanshudhruv/Minifolio#160]
![image](https://github.com/user-attachments/assets/d8946aa6-10f5-4e21-b606-a7f747cf597d)

**The nav bar is not correct for mobile devices.**

**Comment by TheSoumenMondal** [comment]
Assign me this issue and add a  hacktoberfest label

**Comment by divyanshudhruv** [comment]
This issue is already in progress

**Comment by TheSoumenMondal** [comment]
okay
