### ISSUE TITLE
Add social media responsive icon

### ISSUE THREAD

**Issue by MOHIT-IITP** [divyanshudhruv/Minifolio#164]
Thing i will add:
1: Social media logo for contact
2: add and enhance navbar , like add education section in navbar and make it more interactive 
3: add a page where you will add all the project 
![Screenshot 2024-10-10 at 7 36 59 PM](https://github.com/user-attachments/assets/71590f8e-3784-4e98-a0ea-0f44693c879b)

**Comment by divyanshudhruv** [comment]
The social icons on the left look awesome, you can work on it. But the education link in navbar is already fixed,I haven't deployed the latest merge that's why you are unable to see the text in the navbar. You can refer to the commit history...

**Comment by divyanshudhruv** [comment]
The project section is also done, we haven't deployed yet. But you can work on the social links. Good luck for that 👍
