### ISSUE TITLE
✨ Add navigation menu

### ISSUE THREAD

**Issue by divyanshudhruv** [divyanshudhruv/Minifolio#17]
## 🫤 Description

<br>

> Adding navigation menu in the portfolio

<br>

## 📍 Use Case

<br>

> It will make portfolio look more attractive

> Provide easier navigation to different sections

<br>

## 📦 Additional Information

<br>

> Add any other relevant information here.

<br>

## ✋🏻 Upvotes

<br>

> If you support this feature request, add a 👍🏻.

<br>

## 🤔 To-Do

<br>

> If you have specific tasks or action items related to this feature request, list them here.

<br>

## 🌱 Contribute

<br>

> - [ ] I want to contribute 

  <br>
  
## 📌 Related Issue

<br>

> #6

**Comment by Rishikesh-Guptha** [comment]
I would like to contribute by creating the Navbar.

**Comment by Kapileswar-Moharana** [comment]
I would like to add the navigation menu under Hacktoberfest'23 Assign me this @divyanshudhruv

**Comment by divyanshudhruv** [comment]
I think we should wait for all the sections and contributors to complete the task and add the navigation at the end to prevent any further error dur to **`id change of div`**.

**Comment by Kapileswar-Moharana** [comment]
> @Kapileswar-Moharana I think we should wait for all the sections and contributors to complete the task and add the navigation at the end to prevent any further error dur to **`id change of div`**.

Okay

**Comment by Mdfarhan9304** [comment]
Bro see my pull request and merge it. Don't worry it will conflict with other class name

**Comment by vansh-attri** [comment]
Hi, If anyone is not working on this issue, Can you please assign this to me?
