### ISSUE TITLE
🔐🟢 Open [update: refork]: Pull requests/issues will now be accepted. Please refork the repository's main branch for further commits.

### ISSUE THREAD

**Issue by divyanshudhruv** [divyanshudhruv/Minifolio#170]
### 🔒 **Pull Request/Issue Freeze**  
We were temporarily **not accepting any pull requests** until **[16-10-2024]**. This 
wass to allow for planned developments and deployments. Since there are no more conflicts present in any code files, we are accepting new contributions.

### ❓ Why the Freeze?
- We are currently addressing critical updates or refactoring.
- Stabilizing the codebase to ensure all future contributions align with the new changes.
  
### 🤔 What Can You Do?
- You can continue working on your contributions and prepare your pull requests for submission once the freeze is lifted.
- Keep an eye on this **issue** for further updates.
  
<Br>

> **Thank you for your understanding and patience!**  

##  👍 Update
> We are now accepting pull requests and issues.

> The PRe will be merged soon after the opening of it (2-3 days)

**Lets code coders!**

**Comment by divyanshudhruv** [comment]
# 📃 LIST [dev-main]

**`LIST OF SOME TASKS`**

<br>

> Fix education section (add media query) for smaller screens.
- PR: received ✅
- Progress: in-progress ⚙️
- Level: critical ☢️
> Add social links to the landing page
- PR: received ✅
- Progress: in-progress ⚙️
- Level: urgent 🟧
> Add contact section
- PR: received ✅
- Progress: in-progress ⚙️
- Level: normal 🟦
> Add blog section
- PR: received ✅
- Progress: in-progress ⚙️
- Level: normal 🟦
> Update footer UI
- PR: received ✅
- Progress: in-progress ⚙️
- Level: critical ☢️

**Comment by Aakansha-Chavan** [comment]
so we should open a pull request and then wait till it is accepted? @divyanshudhruv

**Comment by divyanshudhruv** [comment]
you can open the pr and issues now
