### ISSUE TITLE
🔥 Add social media links

### ISSUE THREAD

**Issue by divyanshudhruv** [divyanshudhruv/Minifolio#18]
## 🫤 Description

<br>

> Add social media link for the visitors

<br>

## 📍 Use Case

<br>

> Visitors will have multiple ways to get in touch with us.

> It will also help in showcasing our talents.

<br>

## 📦 Additional Information

<br>

> Link should be added in **`contact section`** or in **`footer`**

<br>

## ✋🏻 Upvotes

<br>

> If you support this enhancement, add a 👍🏻.

<br>

## 🤔 To-Do

<br>

> If you have specific tasks or action items related to this enhancement, list them here.

<br>

## 🌱 Contribute

<br>

> - [] I want to contribute 

  <br>

## 🎉 Hacktoberfest

<br>

> - [] I want to participate 

<br>

## 📌 Related Issue

<br>

> #6

**Comment by newtoallofthis123** [comment]
I would like to contribute to this

**Comment by divyanshudhruv** [comment]
Ok, good luck

**Comment by newtoallofthis123** [comment]
Thanks 😄

**Comment by divyanshudhruv** [comment]
@newtoallofthis123 How's the work going ?

**Comment by newtoallofthis123** [comment]
Quite good actually....I am using simple icons for the icons and i am creating a component that takes in the icon name and the color....so the user can add whatever social media icon they need

Will share screenshots once I am satisfied with the design

**Comment by divyanshudhruv** [comment]
Ok, sure

**Comment by divyanshudhruv** [comment]
Hello, please visit [here](https://github.com/divyanshudhruv/Minifolio/issues/1#issuecomment-1739523243)

**Comment by BANGBANG1999** [comment]
Hey @divyanshudhruv can i work on this issue if it's open

**Comment by divyanshudhruv** [comment]
Hi @BANGBANG1999 , unfortunately this issue is being completed by newtoallofthis123

**Comment by AyanGairola** [comment]
Hey @divyanshudhruv  , i would like to contribute , please assign me

**Comment by karankoder** [comment]
Please assign me some issue @divyanshudhruv
