### ISSUE TITLE
Changing the footer design

### ISSUE THREAD

**Issue by MOHIT-IITP** [divyanshudhruv/Minifolio#181]
Aim is to make something like this .
if you want something like this then assign me 
/assign asap
![Screenshot 2024-10-11 at 11 03 56 AM](https://github.com/user-attachments/assets/a98bfa90-95de-4183-b287-e0536afb82c1)

**Comment by divyanshudhruv** [comment]
#170

**Comment by MOHIT-IITP** [comment]
if you wanna make your footer like that then please assign me after 16th october #170 
i would love to contribute in you project.
@divyanshudhruv

**Comment by MOHIT-IITP** [comment]
@divyanshudhruv

**Comment by divyanshudhruv** [comment]
@MOHIT-IITP

**Comment by divyanshudhruv** [comment]
@MOHIT-IITP fork the dev-main branch

**Comment by divyanshudhruv** [comment]
can you share the screenshot of the footer section before oepning the PR?

**Comment by MOHIT-IITP** [comment]
Ok @divyanshudhruv  I will share the ss

**Comment by MOHIT-IITP** [comment]
@divyanshudhruv  How is it?
![Screenshot 2024-10-16 at 8 43 52 PM](https://github.com/user-attachments/assets/468261ae-b1a2-430f-829f-dde949c83483)

**Comment by divyanshudhruv** [comment]
@MOHIT-IITP whoa, that is amazing. wow. It is looking so cool

**Comment by MOHIT-IITP** [comment]
@divyanshudhruv  now can i create pr

**Comment by divyanshudhruv** [comment]
@MOHIT-IITP yeah

**Comment by MOHIT-IITP** [comment]
@divyanshudhruv  in which branch i have to create pr

**Comment by divyanshudhruv** [comment]
@MOHIT-IITP you can create PR in main branch only. I'll fix it then

**Comment by divyanshudhruv** [comment]
@MOHIT-IITP yea, I'll review it then I'll merge it. Don't worry, it always shows
