### ISSUE TITLE
Implement Dark Mode Feature

### ISSUE THREAD

**Issue by CodeGallantX** [divyanshudhruv/Minifolio#188]
**Description:**  
I would like to implement a dark mode feature for the Minifolio project to enhance user experience, especially in low-light environments. This feature will allow users to toggle between light and dark themes.

**Proposed Changes:**
- Create a dark mode stylesheet.
- Add a toggle button in the navigation menu for the dark mode.
- Test for cross-browser compatibility.

**Acceptance Criteria:**
- The dark mode should be visually appealing and functional across all pages.
- The toggle button should be easy to access.

**Additional Notes:**  
This feature could significantly improve accessibility and user comfort. I plan to work on this feature over the next few days.

**Comment by PradeepFSTdhane123** [comment]
could you please assigh to me

**Comment by divyanshudhruv** [comment]
#2 #170

you can create a PR but before doing that you may share a screenshot or a short video

**Comment by PradeepFSTdhane123** [comment]
screenshot about what?
