### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by MichaelHopeDavid** [divyanshudhruv/Minifolio#19]
The About Section is missing an icon 
TL;DR also seems incomplete

**Comment by divyanshudhruv** [comment]
Can you provide the issue in detail ?

**Comment by divyanshudhruv** [comment]
Hello, actually that's a bug that make user see no icon in the about section. No need to worry it will be fixed automatically

**Comment by abhaygzb15** [comment]
ok thanks for informing. @divyanshudhruv 
I am a beginner in open source. So, is there any other issue which I can work upon and start gaining my first open source experience. Can u guide me ?

**Comment by divyanshudhruv** [comment]
Ok, you can start open-source by contributing to [this repository](https://github.com/firstcontributions/first-contributions)

If I have any issue in progress, I will contact you. Good luck

**Comment by Pratikdate** [comment]
Assign me i will work on it
