### ISSUE TITLE
improve the footer 

### ISSUE THREAD

**Issue by Vardhan-Harsh07** [divyanshudhruv/Minifolio#193]
![image](https://github.com/user-attachments/assets/cf3728ed-6018-4aac-8519-2c2a6df70579)
can make the footer like this or better

**Comment by divyanshudhruv** [comment]
You can make and then open PR

**Comment by Vardhan-Harsh07** [comment]
ok sure why not @divyanshudhruv

**Comment by Vardhan-Harsh07** [comment]
@divyanshudhruv got it

**Comment by Vardhan-Harsh07** [comment]
@divyanshudhruv check the pull request #195
