### ISSUE TITLE
🔥 Animation while scrolling

### ISSUE THREAD

**Issue by divyanshudhruv** [divyanshudhruv/Minifolio#20]
## 🫤 Description

<br>

> Add some animations while scrolling [Suggested by @Kapileswar-Moharana]

<br>

## 📍 Use Case

<br>

> Portfolio will look more playful and cool

> Make portfolio look professional.

<br>

## 📦 Additional Information

<br>

> We can use **`scroll-reveal`** or **`locomotive-scroll`**

<br>

## ✋🏻 Upvotes

<br>

> If you support this enhancement, add a 👍🏻.

<br>

## 🤔 To-Do

<br>

> If you have specific tasks or action items related to this enhancement, list them here.

<br>

## 🌱 Contribute

<br>

> - [] I want to contribute 

  <br>

## 🎉 Hacktoberfest

<br>

> - [] I want to participate 

<br>

## 📌 Related Issue

<br>

> None

**Comment by Riddhick** [comment]
Hi, can you add hacktoberfest tag and assign it to me .

**Comment by divyanshudhruv** [comment]
Hi, actually I am currently doing this issue. So unfortunately I cannot assign you this issue. Good luck for
