### ISSUE TITLE
Add Dynamic text typing animation 

### ISSUE THREAD

**Issue by mathanraj0601** [divyanshudhruv/Minifolio#21]
## Adding Dynamic Typing text animation 
- a dynamic text animation on your website, featuring roles like 'Developer,' 'Blogger,' 'YouTuber,' and more,
-  we can use animation in the static 'Unknown Developer' or 'I'm a Developer element/area
- This makes the minifolio look cool

![image](https://github.com/divyanshudhruv/Minifolio/assets/98396468/d8a32b78-c0cd-4423-964f-468e0973fed7)
![image](https://github.com/divyanshudhruv/Minifolio/assets/98396468/9c951c3f-49ea-44a1-a6e1-91f1ff0efcb9)

We can add in both or just one

**Comment by mathanraj0601** [comment]
I have the action plan for this cool animation @divyanshudhruv : )

**Comment by divyanshudhruv** [comment]
Ok @mathanraj0601 . Good luck. I will assign you the task tomorrow. You can open pr during hacktoberfest.

**Comment by mathanraj0601** [comment]
Sure Divyan sounds great :) 
Divyan can we add the animation in both elements/places or in any one of them?

**Comment by divyanshudhruv** [comment]
Your wish, good luck

**Comment by mathanraj0601** [comment]
Thanks, @divyanshudhruv. I will make it look appealing. Looking forward to getting assigned to start my work.

**Comment by divyanshudhruv** [comment]
Assigned, you may open pr during hacktoberfest :)

**Comment by mathanraj0601** [comment]
Yess! @divyanshudhruv

**Comment by divyanshudhruv** [comment]
Hello, please visit [here](https://github.com/divyanshudhruv/Minifolio/issues/1#issuecomment-1739523243)
