### ISSUE TITLE
Features that i can contribute to

### ISSUE THREAD

**Issue by Znoy108x** [divyanshudhruv/Minifolio#22]
(1) Page Load Animation.
(2) Projects Section with Animation.
(3) Experience Section.
(4) Education Section.

**Comment by divyanshudhruv** [comment]
I think you can contribute to the page loading animations as rest are being in progress by many contributors. Good luck I will assign the page loading animations task to you. You can open pr during hacktoberfest.

**Comment by divyanshudhruv** [comment]
You can open pr during hacktoberfest

**Comment by abhaygzb15** [comment]
@divyanshudhruv I would like to work on the Education section. Can you assign this issue to me?

**Comment by divyanshudhruv** [comment]
@abhaygzb15 I think education section is not being added to the portfolio, so unfortunately I cannot assign it to you. Btw you can come with new ideas about the enhancements, features etc. Good luck, and sorry as I cannot assign the issue

**Comment by divyanshudhruv** [comment]
Hello, please visit [here](https://github.com/divyanshudhruv/Minifolio/issues/1#issuecomment-1739523243)

**Comment by divyanshudhruv** [comment]
@Znoy108x see the pull request.

**Comment by Znoy108x** [comment]
@divyanshudhruv hello divyanshu did you merged my pr?

**Comment by divyanshudhruv** [comment]
Not now , I'll merge after 6oct
