### ISSUE TITLE
Add Click Me button animation

### ISSUE THREAD

**Issue by ferrorenan** [divyanshudhruv/Minifolio#23]
Add an animation for the Click Me Button

**Comment by ferrorenan** [comment]
hey @divyanshudhruv 

Could you add the Hacktoberfest tag and assign this issue to me?!

I would like to add a really cool animation to the button!

**Comment by divyanshudhruv** [comment]
Ok, you can also try to add background animation to the `Know more` button also.

**Comment by divyanshudhruv** [comment]
Good luck @ferrorenan

**Comment by divyanshudhruv** [comment]
Hello, please visit [here](https://github.com/divyanshudhruv/Minifolio/issues/1#issuecomment-1739523243)

**Comment by SofiaHerrera27** [comment]
Hello, I would like to help contribute to your project.

**Comment by Hithaish2001** [comment]
hey @divyanshudhruv can you please assign this issue this issue to me so that i can contribute a beautiful animated button

**Comment by AkshatJangid787** [comment]
can you please assign me this issue?

**Comment by Akshatverma01** [comment]
Hey can you please assign this issue to me. I will definitely make worthfull contribution. I am good at front end.

**Comment by Akshatverma01** [comment]
Hey ! I have good at front-end and made many front-end projects with animations. I can do this better. Please assig this issue to me.
