### ISSUE TITLE
Add terminal type text animation 

### ISSUE THREAD

**Issue by VasuK111** [divyanshudhruv/Minifolio#24]
![image](https://github.com/divyanshudhruv/Minifolio/assets/117103753/67f11b59-8cd5-438a-9fa8-5aea4850a462)
Like this one. The text would move out like that in any common Linux GNU terminal. That would make the site look even more cool. 
A Scrollspy can also be added on the landinfg page infact if you wish to, that would make the page more easy to navigate through once a lot of features which people in other issues have raised gets added. 
Hover animation for items like
Web UI&UX
Figma
HTML & CSS..... items present can make the overall outlook supercool I suppose.

**Comment by VasuK111** [comment]
I would be grateful if I'm given the opportunity to demonstrate how these minor changes can bring a lot of improvement in the overall outlook of the page.

**Comment by divyanshudhruv** [comment]
@VasuK111 , Thanktou for your suggestion but this same feature is In progress by another contributors. So, unfortunately we cannot assign same issue to 2 people. Btw good luck,
