### ISSUE TITLE
🔥 Improved footer

### ISSUE THREAD

**Issue by divyanshudhruv** [divyanshudhruv/Minifolio#25]
## 🫤 Description

<br>

> Improving the footer by incorporating a more appropriate sentence.

<br>

## 📍 Use Case

<br>

> Give more details about the license, authors, etc.

<br>

## 📦 Additional Information

<br>

> Add any other relevant information here.

<br>

## ✋🏻 Upvotes

<br>

> If you support this enhancement, add a 👍🏻.

<br>

## 🤔 To-Do

<br>

> If you have specific tasks or action items related to this enhancement, list them here.

<br>

## 🌱 Contribute

<br>

> - [] I want to contribute 

  <br>

## 🎉 Hacktoberfest

<br>

> - [] I want to participate 

<br>

## 📌 Related Issue

<br>

> #1

**Comment by Vishal-1004** [comment]
hii @divyanshudhruv 
So Want i want to do is that i want to enhance the footer
from this
Template Developed With By <> Divyanshu Dhruv
To
@2023 All Rights Reserved | Template Developed With By <> Divyanshu Dhruv

More over the year "2023" will be updated dynamically with the help of JS, so that we dont need to manually come to  the page and update it every year.
This will  be  the maximum enhancement which can be done to the footer for now.

**Comment by divyanshudhruv** [comment]
Ok, good luck. Assigning the issue. You may open pr in **`development`** branch during hacktoberfest

**Comment by Vishal-1004** [comment]
Thanks for assigning the task to me.
I will make the pull request on 1st of October

**Comment by divyanshudhruv** [comment]
Nice. But you can either increase the width of the footer or put the `Template develpoed by <> Divyanahu Dhruv` on a new line to avoid any congestion.

**Comment by divyanshudhruv** [comment]
Cool. The desktop one looks nice. Also you may give space after copyright symbol to make it more clear

**Comment by Vishal-1004** [comment]
Ok i will leave space after the copyright's symbol.
Can you tell me which words would you like to be made bold.

**Comment by divyanshudhruv** [comment]
Cool. You may bold the copyright icon and the year and also put space after `|`

**Comment by Vishal-1004** [comment]
Roger sir

**Comment by divyanshudhruv** [comment]
Can you also send the screenshot after you did the issue? You may open pr into main branch

**Comment by Vishal-1004** [comment]
Here you go,

I have made all the changes as you ask me to do, hope this satisfices your needs
![Screenshot (1385)](https://github.com/divyanshudhruv/Minifolio/assets/94651481/17e24f99-90dc-45da-9336-1df08173af8e)

**Comment by divyanshudhruv** [comment]
Cool. I think remove the bold and if possible decrease the line height, else it's OK! Good job @Vishal-1004

**Comment by Vishal-1004** [comment]
![Screenshot (1386)](https://github.com/divyanshudhruv/Minifolio/assets/94651481/adf0e93c-f0ee-4586-afd1-999081bfe22d)

I Guess the changes are clearly implemented and seen in this screen shot. Let me know  if can make a pull request with this and that to in branch i am suppose to make the pull request

**Comment by divyanshudhruv** [comment]
Cool you can open pr. Good job

**Comment by divyanshudhruv** [comment]
Congrats @Vishal-1004
