### ISSUE TITLE
[FEAT] : Make the Favicon more attractive.

### ISSUE THREAD

**Issue by bhaavvya** [divyanshudhruv/Minifolio#28]
Please assign me to add this feature.

**Comment by bhaavvya** [comment]
heyy @divyanshudhruv 
Can you add hacktoberfest tag and Enhancement tag to my issue and assign me under hacktoberfest.

**Comment by divyanshudhruv** [comment]
Hi, can you describe the feature on more detail?

**Comment by bhaavvya** [comment]
![image](https://github.com/divyanshudhruv/Minifolio/assets/110487270/116298b9-5cd6-4af3-88d2-12408360e345)

**Comment by bhaavvya** [comment]
![image](https://github.com/divyanshudhruv/Minifolio/assets/110487270/1d493235-baa3-4790-8e42-0777da26797b)

**Comment by bhaavvya** [comment]
![image](https://github.com/divyanshudhruv/Minifolio/assets/110487270/6e54095d-8202-4215-87d8-4d9e8ee5a75e)

**Comment by bhaavvya** [comment]
![image](https://github.com/divyanshudhruv/Minifolio/assets/110487270/2d3bd81b-377e-49d3-81cc-7b77dd414aac)

**Comment by bhaavvya** [comment]
![image](https://github.com/divyanshudhruv/Minifolio/assets/110487270/72aba2cf-2262-4e49-a780-fe8c2cf2a183)

**Comment by divyanshudhruv** [comment]
Oh, I think we should leave the favicon task for the end. Btw thanks for sharing the images
