### ISSUE TITLE
README top image link broken

### ISSUE THREAD

**Issue by josepmonclus** [divyanshudhruv/Minifolio#3]
The top image link in README.md file its broken (or from a private repo it seems). 

![image](https://github.com/divyanshudhruv/Minifolio/assets/3169428/7db7db51-3f41-4b5f-8f57-c77750a209f8)

**Comment by divyanshudhruv** [comment]
Ok. Will try to fix that...

**Comment by mathanraj0601** [comment]
Can i fix it divyan?

**Comment by divyanshudhruv** [comment]
Ok @mathanraj0601

**Comment by mathanraj0601** [comment]
![Minifolio](https://github.com/divyanshudhruv/Minifolio/assets/98396468/d7b4260c-28d5-49a9-b379-f112f6f4e7eb)
Can you clarify whether The above image needs to be replaced or used in the broken link of the readme 
if yes, Then the action plan
1. change the src of the image to this image
2. Update the image tag with alt text minifolio=logo

can I proceed ?

**Comment by divyanshudhruv** [comment]
Thankyou @mathanraj0601 , will merge it follow Minifolio for more information

**Comment by divyanshudhruv** [comment]
Just found that, some bug was there. I fixed it recently as many people were facing the same issue . Mathan Raj you can contribute in hacktoberfest 2023. But I appreciate your work. Good job

**Comment by mathanraj0601** [comment]
Okay sure divyan if you have any feature/ issue I like to contribute :)

**Comment by divyanshudhruv** [comment]
@mathanraj0601 , can you add some cool animations in the portfolio, like text fading, scroll animation etc.

**Comment by mathanraj0601** [comment]
Sure divyan i will come up ideas and action plan. If your are moving the project to react or any other frame we will try to have a const with json object so that user can simple update all their details at one without distributing or modifying the code base :) 

See you soon some cool ideas and meanwhile if you have any issue working with html, css, js assign to me:)

**Comment by divyanshudhruv** [comment]
Good luck. We can think of that
