### ISSUE TITLE
Add Navbar 

### ISSUE THREAD

**Issue by bhaavvya** [divyanshudhruv/Minifolio#31]
**Description **
Navbar will contain important details like email-id , phone no. , address and so on and on the right side it will have About , Skills, Projects , Contact section which will redirect to the respective section.
Like this
![image](https://github.com/divyanshudhruv/Minifolio/assets/110487270/8bfce7f0-2397-4197-bf76-ddee0525aeac)

please assign me under hacktoberfest.

**Comment by divyanshudhruv** [comment]
@bhaavvya please see #17

**Comment by divyanshudhruv** [comment]
We will make the navbar at the end, when all the sections are present.
