### ISSUE TITLE
Add Skills section 

### ISSUE THREAD

**Issue by AMANMUHAL** [divyanshudhruv/Minifolio#43]
To enhance its visual appeal of  Minifolio 
example :: 
![image](https://github.com/divyanshudhruv/Minifolio/assets/101124129/e1a447ba-1b25-46e4-95dd-b16b584435c8)

**Comment by AMANMUHAL** [comment]
@divyanshudhruv please assign this issue to me under hacktoberfest

**Comment by divyanshudhruv** [comment]
Hi, actually I am doing this issue so unfortunately can't assign to you. Good luck. See #14

**Comment by AMANMUHAL** [comment]
No problem ,, can i make issue of My projects/ Contact Me

**Comment by divyanshudhruv** [comment]
@AMANMUHAL ok good luck

**Comment by AMANMUHAL** [comment]
I closed this issue 43 , will you assign me the related issue

**Comment by divyanshudhruv** [comment]
Sure
