### ISSUE TITLE
Make changes to the Footer

### ISSUE THREAD

**Issue by Sujal-2820** [divyanshudhruv/Minifolio#45]
The Footer Looks a bit boring at the moment, with only the Copyright text and salutation solely being shown. 

Adding a good looking Footer with some reference Attributes/Links and giving it a proper layout would make the Footer and the Webpage look Good!!

![Footer_IMG](https://github.com/divyanshudhruv/Minifolio/assets/112640952/242ebea3-11d9-4fbe-986b-b01048c3a2f0)

**Comment by Sujal-2820** [comment]
@divyanshudhruv Can you please Label this issue by "Hacktoberfest" and assign it to me.

**Comment by Sujal-2820** [comment]
I would also try adding the Social Icons which would enhance its appearance.

**Comment by divyanshudhruv** [comment]
I think it look fine at this stage. We will add more links after we are done with other sections

**Comment by divyanshudhruv** [comment]
Will surely contact you if needed. Good luck
