### ISSUE TITLE
✏️ Style Edits to the Home Page

### ISSUE THREAD

**Issue by vcavanna** [divyanshudhruv/Minifolio#5]
## 🫤 Description

<br>

> I'm offering a style correction, not a typo issue. There are no problems with the grammar from what I saw, but some style issues to make it sound better for the below lines.

<br>

## 📍 Location

<br>

> File name: /index.html

> Line number: 17, 33
> URL: https://divyanshudhruv.github.io/Minifolio/

<br>

## 🧪 Correction

<br>

> Line 17: "<a class="button" href="#about">Learn more</a>"
> Line 33: I design websites. That's the long and short of it. I design UI and UX with Sketch, Design, and pretty decent HTML and CSS, while dabbling with Javascript and Java.

 <br>
 
## 📦 Additional Information

<br>

> Add any other relevant information here.

<br>
  
## 📌 Related Issue

<br>

> Link to other issues related to this problem

**Comment by vcavanna** [comment]
I also have another question. I don't really do frontend design. Are "sketch" and "design" tools that people use to design websites? If so, it might be useful to link or bold them so they stand out more. Design especially makes me just think of the verb "to design".

**Comment by divyanshudhruv** [comment]
Yes, true. Thank you for noticing the error. If you want, you can replace the error. But the correction in **`line:33`** doesn't sound suitable. Try to make more better correction to the sentence . **If you want may I assign the work to you ?** You can contribute(open pull request after 1 oct for hacktoberfest) during hacktoberfest.

**Comment by vcavanna** [comment]
Yes, assign it to me! I'll think about how to reword **`line:33`**. Right now I'm thinking it needs more active verbs (i.e. from [this list](https://www.indeed.com/career-advice/resumes-cover-letters/action-verbs-to-make-your-resume-stand-out)).

**Comment by divyanshudhruv** [comment]
Ok , Assigning to you... Good luck

**Comment by aahanatiwari** [comment]
hi, i'd like to participate in fixing this issue (hacktoberfest)

**Comment by divyanshudhruv** [comment]
@vcavanna  ?

**Comment by SofiaHerrera27** [comment]
Hello, I would like to help contribute to your project in this issue.

**Comment by vcavanna** [comment]
Hi @divyanshudhruv it'll be done end of day
