### ISSUE TITLE
Adding a Service section

### ISSUE THREAD

**Issue by Dhaneshwarguiyan** [divyanshudhruv/Minifolio#51]
## 🫤 Description

<br>

> This section will be containing all types of services that  portfolio owner will be giving. 

<br>

## 📍 Use Case

<br>

> It can be used to display the work such as Web Development ,UI/UX Designer , SEO Expert.

<br>

## ✋🏻 Upvotes

<br>

> If you support this feature request, add a 👍🏻.

<br>

## 🌱 Contribute

<br>

> - [x] I want to contribute 

  <br>

## 🎉 Hacktoberfest

<br>

> - [X] I want to participate 

<br>

## 📌 Prototype

<br>

![Screenshot from 2023-10-03 14-46-10](https://github.com/divyanshudhruv/Minifolio/assets/116065351/f499a7c6-ff4e-460b-8b51-08cb06bf52c7)

**Comment by divyanshudhruv** [comment]
Ook, good luck

**Comment by arjungupta01** [comment]
Hyy assign this to me

**Comment by divyanshudhruv** [comment]
Ok

**Comment by weberankit** [comment]
@divyanshudhruv is this issue resolved ?? if not then plz assign it to me

**Comment by harshitadharamansharma** [comment]
@divyanshudhruv Please assign this to me, if not resolved yet.

**Comment by Kawaljeet-943** [comment]
Hi @divyanshudhruv Is this issue still being worked on? If not, I would love to contribute to adding the services section. Please let me know. Thanks!

**Comment by divyanshudhruv** [comment]
> Hi @divyanshudhruv Is this issue still being worked on? If not, I would love to contribute to adding the services section. Please let me know. Thanks!
>  @Kawaljeet-943 yes we are looking for contribution. I've added you as assignee

**Comment by Kawaljeet-943** [comment]
Thank you for assigning this issue to me! I will start working on adding the services section now.

**Comment by divyanshudhruv** [comment]
#98
