### ISSUE TITLE
Nav Bar Section

### ISSUE THREAD

**Issue by Kapileswar-Moharana** [divyanshudhruv/Minifolio#55]
Create a navbar Section in which All of the sections will added and placed top right corner, Clicking those sections on the nav bar will take you to their respective.

**Comment by Kapileswar-Moharana** [comment]
Assign This Issue To me under Hacktoberfest'23

**Comment by divyanshudhruv** [comment]
Hey a tally I am crating the navbar due to confusion among all the contributors. You can create a contact section

**Comment by Kapileswar-Moharana** [comment]
> Hey actually I am crating the navbar due to confusion among all the contributors. You can create a contact section 

Ok

**Comment by divyanshudhruv** [comment]
Ok thnx, you can create navbar

**Comment by Dcode36** [comment]
Assign this to me
###
