### ISSUE TITLE
Input from user

### ISSUE THREAD

**Issue by kom-senapati** [divyanshudhruv/Minifolio#57]
I just visited the deployed website and I noticed the portfolio direct.
Let us add another page before that portfolio, 
maybe it can take inputs[name, skills, projects(name, desc, link), education, work experience, contact details] and a button to generate the portfolio so that non-tech users can easily create one portfolio.

**Comment by divyanshudhruv** [comment]
Thnx but we are working on it

**Comment by divyanshudhruv** [comment]
Actually we are working on the first idea, input the values. If you want to add the second idea, generate the portfolio in one click, you are free to open pr. Good luck

**Comment by devyani277** [comment]
Hey Can You please assign it to me
