### ISSUE TITLE
👉 Add Cursor Animation on MouseMove 👈

### ISSUE THREAD

**Issue by alinasoy** [divyanshudhruv/Minifolio#67]
I want to add cursor animation
Can you assign me on this issue?

**Comment by divyanshudhruv** [comment]
can you describe a bit more and also some screenshot if possible

**Comment by alinasoy** [comment]
https://github.com/divyanshudhruv/Minifolio/assets/127585848/157d87cd-5468-4d4d-8b5f-46371ef2e36b

**Comment by amrahs02** [comment]
Hey , Can you assign this to me?

**Comment by Shivang-v-erm-a** [comment]
can you please assign it to me, i will do the task in much concise and customizable manner

**Comment by divyanshudhruv** [comment]
@alinasoy  That looks awesome! However, I think a circular cursor would be a nice replacement for the default one. Thanks for your contribution!
