### ISSUE TITLE
Changing the color of Button

### ISSUE THREAD

**Issue by Sujal-12345** [divyanshudhruv/Minifolio#75]
Hey @divyanshudhruv 
I would like to change the color of Button on Hovering it to red

please assign me this issue and label it as Hacktoberfest 2023.

**Comment by anushkapal28** [comment]
Hello! I'm interested in working on this task. I have experience with HTML and CSS , and I'm eager to contribute. I would like to change the color of the button. Please consider assigning this to me, and I'll get started right away. Thanks!

**Comment by PraffulPatel27** [comment]
Hello,
I'm eager to contribute to this issue and would appreciate it if you could assign me to work on it. I'm committed to delivering quality results and will provide a screenshot and a short video in accordance with your guidance. 

Button 
![buttons](https://github.com/divyanshudhruv/Minifolio/assets/110104505/53cf46ef-9c13-4122-956e-d1c772baf2cd)

When hover, the colour red
![hover red](https://github.com/divyanshudhruv/Minifolio/assets/110104505/07fb3fcc-a5a5-4494-a9f9-ad1c7f8c7a20)

When hover it colour red with red shadow effect 
![hover red with shadow effect](https://github.com/divyanshudhruv/Minifolio/assets/110104505/a265b6e2-2aa3-4f99-8af8-da50bbe35bc9)

Video of hover button

https://github.com/divyanshudhruv/Minifolio/assets/110104505/8c710614-9e31-48d7-a79b-1d8a8b7e4680

Thank you!
