### ISSUE TITLE
Adding navigation bar

### ISSUE THREAD

**Issue by Nupur19nj** [divyanshudhruv/Minifolio#77]
Hello Divyanshu!
I want to contribute in your repo by adding the navigation bar on top.
Please assign me this issue under Hacktober-accepted tag!

**Comment by anushkapal28** [comment]
Hello! I'm interested in working on this task. I have experience with HTML and CSS , and I'm eager to contribute. Please consider assigning this to me, and I'll get started right away. Thanks!
