### ISSUE TITLE
Adding Your Experience and Schooling and Skills in Code Format Looks Attractive

### ISSUE THREAD

**Issue by Kapileswar-Moharana** [divyanshudhruv/Minifolio#8]
Creating an Navigation Bar which will take me to my all details section which is written in Code Format Like this 

![Screenshot 2023-09-27 013001](https://github.com/divyanshudhruv/Minifolio/assets/129049677/f198d8b1-e33f-497d-aca2-d3e0426d0ff8)

Assign this to  me ...

**Comment by divyanshudhruv** [comment]
I think we can close this issue as I am myself designing the skills section.

**Comment by Kapileswar-Moharana** [comment]
> @Kapileswar-Moharana I think we can close this issue as I am myself designing the skills section.

Okay
