### ISSUE TITLE
Back to top button visibility

### ISSUE THREAD

**Issue by Sharjeel-Afridi** [divyanshudhruv/Minifolio#88]
**Button is visible when the page first loads, it should have visibility hidden and should get visibility when the condition meets.**
<img width="950" alt="image" src="https://github.com/divyanshudhruv/Minifolio/assets/52808124/1dcf79de-13f4-4e2e-bc77-7046b711f77e">

**Comment by divyanshudhruv** [comment]
@Sharjeel-Afridi Thanks for finding the bug

Do you want to work on this issue ?

**Comment by Sharjeel-Afridi** [comment]
yeah, sure!

**Comment by divyanshudhruv** [comment]
Ok
