### ISSUE TITLE
Add a Projects Section

### ISSUE THREAD

**Issue by avisha191** [divyanshudhruv/Minifolio#96]
A section to showcase the user's past projects with descriptions, links or demos.
Kindly assign me this under Hacktoberfest 2024

**Comment by Shivang-v-erm-a** [comment]
can you assign it to me

**Comment by divyanshudhruv** [comment]
> A section to showcase the user's past projects with descriptions, links or demos. Kindly assign me this under Hacktoberfest 2024

That's a great idea! Would you like to work on it?

**Comment by avisha191** [comment]
Yes

**Comment by divyanshudhruv** [comment]
@avisha191 Ok, assigned to you. Good luck

**Comment by divyanshudhruv** [comment]
@avisha191 what's the status ?

**Comment by marsianjohncarter** [comment]
@divyanshudhruv If avisha isn't going to be working on this, may take up the task?

**Comment by avisha191** [comment]
Yes, I am working on it.

**Comment by avisha191** [comment]
Created pull request

**Comment by avisha191** [comment]
Thanks
